### ISSUE TITLE
Export functions

### ISSUE THREAD

**Issue by bgreenwell** [AFIT-R/DecisionAnalysis#2]
Currently none of the functions are exported. So each will need a `#' @export` tag in the roxygen documentation. Otherwise you'll have to use `:::` to call any of the packages functions; for example, `MODA:::MAVF_breakout`.

**Comment by bgreenwell** [comment]
For now, you can simply add `exportPattern("^[^\\.]")` to the `NAMESPACE` file to export all functions that don't start with a `.`.

**Comment by bradleyboehmke** [comment]
`#' @export` tags added.
